### ISSUE TITLE
Use internal tags for formatting tags

### ISSUE THREAD

**Issue by jasonwhat** [jbfriedrich/lazo#1]
This is a great theme and really cool way of showing what Ghost can do just at the theme level. One question: why not have the Quote and link tags use the [internal tags](https://help.ghost.org/hc/en-us/articles/224169868-Internal-Tags-Beta) feature rather than regular tags?

**Comment by jbfriedrich** [comment]
Thanks! It's a hobby project for me and I am happy if someone else finds it useful. I am not using the internal tags, because you cannot use them for example in menus. When I want an overview of all links, I would put a link in the menu that points to "/tag/link". This is not possible with internal links. I could of course create a custom page, as I did with the search page. But the concepts feels weird to me that I can create a custom page, but for it to be visible I have to create en empty page in the UI. I hope that this will be a bit more streamlined in version 1.0 of Ghost.
